name: Test and Deploy to Vercel

on:
  push:
    branches:
      - main
      # - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

    # - name: Run tests
    #   run: npm run test

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Branch: ${{ github.ref }}"
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "Deploying to Production (master)..."
            vercel --prod --confirm --token=$VERCEL_TOKEN
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "Deploying to Preview (develop)..."
            vercel --confirm --token=$VERCEL_TOKEN
          else
            echo "Branch ${{ github.ref }} not configured for deploy. Skipping."
          fi
